# Generated by Django 4.0 on 2021-12-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='publish datae')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update post')),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='photo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auth.user', verbose_name='user_created')),
            ],
            options={
                'verbose_name': 'post',
                'ordering': ('-publish_date',),
            },
        ),
    ]
