# Generated by Django 4.0 on 2021-12-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('content_commnet', models.TextField(verbose_name='comment text')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='comment date')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ('-comment_date',),
            },
        ),
    ]
